name = "my-portfolio-windowed"
compatibility_date = "2024-09-18"

[build]
command = "pnpm build:cf"

[site]
bucket = ".vercel/output/static"

# Required for Cloudflare Pages
pages_build_output_dir = ".vercel/output/static"
